### ISSUE TITLE
师傅您好，请问这个项目可以反编译spidermonkey 33 版的jsc吗？

### ISSUE THREAD

**Issue by chansonyan** [Mas0nShi/jscHookR#2]
我是逆向小白，最近在研究怎么破解我正在玩的手游，想实现去除两回合后才能一键跳过的限制。

so文件放入ida，在applicationDidFinishLaunching里没有密钥，jsc文件前几个字节是：2CC073B9，应该是spidermonkey 33 

[main.jsc.zip](https://github.com/Mas0nShi/jscHookR/files/11004057/main.jsc.zip)

请师父指点，万分感激！

**Comment by Mas0nShi** [comment]
从文件来看是sipdermonkey之类的字节码，jscHookR不适用于spidermonkey，你可以参考这个https://github.com/yeyiqun/cocos2d-jsc-decompiler

**Comment by chansonyan** [comment]
> 从文件来看是sipdermonkey之类的字节码，jscHookR不适用于spidermonkey，你可以参考这个https://github.com/yeyiqun/cocos2d-jsc-decompiler

好的，感谢，我研究研究，看能否反编译出来。
